### ISSUE TITLE
post-install script should not depend on git

### ISSUE THREAD

**Issue by chanadian** [hemanth/blns#4]
Hi, we ([FiftyThree](https://github.com/FiftyThree)) recently installed this npm module and we're so glad that we have access to blns! However, some of our environments do not have `git` installed. So when we deploy to those environments the installation fails due to [`post-install`](https://github.com/hemanth/blns/blob/master/package.json#L17). We have removed that script for now in our repo, but would be good not to assume that installation environments have `git`.

Thanks,
Andrew Chan

**Comment by hemanth** [comment]
Thanks for raising this concern, will the below help?

``` sh
[[ -x $(which git) ]] && git submodule update --init --recursive || echo 'You don/'t have git installed, so can/'t update the list'
```

**Comment by chanadian** [comment]
Yes that would be great! Thanks @hemanth
